Update pipeline-ai-impact-full.yml

diff --git a/.github/workflows/pipeline-ai-impact-full.yml b/.github/workflows/pipeline-ai-impact-full.yml
--- a/.github/workflows/pipeline-ai-impact-full.yml
+++ b/.github/workflows/pipeline-ai-impact-full.yml
@@ -19,36 +19,25 @@ jobs:
 
       - name: Authenticate with Keycloak
         id: keycloak_auth
+        shell: bash
         run: |
-        # Define the URL and credentials
-            $authUrl = "http://auth.gftaiimpact.local/realms/ai-impact/protocol/openid-connect/token"
-            $headers = @{
-                "Content-Type" = "application/x-www-form-urlencoded"
-            }
+          TOKEN_RESPONSE=$(curl -s -X POST 'http://auth.gftaiimpact.local/realms/ai-impact/protocol/openid-connect/token' \
+            -H 'Content-Type: application/x-www-form-urlencoded' \
+            -d 'client_id=ai-impact-client' \
+            -d "username=administrator" \
+            -d "password=Gft@2025" \
+            -d "scope=openid" \
+            -d "grant_type=password")
 
-            $body = @{
-                client_id  = "ai-impact-client"
-                username   = "administrator"
-                password   = "Gft@2025"
-                scope      = "openid"
-                grant_type = "password"
-            }
+          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
 
-            # Send the POST request
-            $response = Invoke-RestMethod -Uri $authUrl -Method Post -Headers $headers -Body $body
+          if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" == "null" ]; then
+            echo "Failed to obtain access token"
+            echo "$TOKEN_RESPONSE"
+            exit 1
+          fi
 
-            # Extract the access token
-            $ACCESS_TOKEN = $response.access_token
-
-            # Check if access token is empty or null
-            if (-not $ACCESS_TOKEN -or $ACCESS_TOKEN -eq "null") {
-                Write-Host "Failed to obtain access token"
-                Write-Host ($response | ConvertTo-Json -Depth 10)  # Print the full response
-                exit 1
-            }
-
-            # Save token to GitHub environment
-            "access_token=$ACCESS_TOKEN" | Out-File -FilePath $env:GITHUB_ENV -Append
+          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_ENV
 
       - name: Checkout the branch
         run: |
